# Generated by Django 5.1.1 on 2025-01-17 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_photo', models.ImageField(blank=True, null=True, upload_to='media/products/')),
                ('prod_name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField()),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('inventory_prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.productinventory')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_line2', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('CC', 'Credit Card'), ('GC', 'GCash'), ('PM', 'PayMaya')], max_length=2)),
                ('card_no', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
