# Generated by Django 5.1.1 on 2024-12-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email_address', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_photo', models.ImageField(blank=True, null=True, upload_to='media/products/')),
                ('prod_name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField()),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('inventory_prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.productinventory')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_line2', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'PayPal'), ('GC', 'GCash'), ('PM', 'PayMaya'), ('BA', 'Bank Account')], max_length=2)),
                ('acc_no', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
