# Generated by Django 5.1.1 on 2025-01-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
